import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ThemeContextProvider } from "@/context/ThemeContext";
import { AuthProvider } from "../Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeContextProvider>
            <ToastContainer />
            <div>
              <div className=" w-screen sticky top-0 z-50 bg-slate-200 text-black ">
                <Navbar />
              </div>
              <div className="flex flex-col bg-white text-black w-[100vw] min-h-[500px] overflow-x-hidden items-center ">
                {children}
              </div>
            </div>
            <div className=" w-screen bg-slate-200 text-black ">
              <Footer />
            </div>
          </ThemeContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
